name = "memos-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-06-01"

compatibility_flags = ["nodejs_compat"]

[vars]
LOG_LEVEL = "info"
BASE_URL = "https://memos.example.com"

# Secrets - set via wrangler secret put
# JWT_SECRET
# R2_ACCOUNT_ID  
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
# R2_BUCKET

[[d1_databases]]
binding = "DB"
database_name = "memos"
database_id = "2763bc42-7827-440f-8a4a-894486b38c60"

[env.staging]
name = "memos-cloudflare-staging"

[env.production]
name = "memos-cloudflare-production" 